// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    return $('body > header nav a').click(function(e) {
      $('body > header nav li').removeClass('selected');
      return $($(e.target).parent()).addClass('selected');
    });
  });

}).call(this);
