// Generated by CoffeeScript 1.4.0
(function() {

  this.yPositions = [];

  $(function() {
    var image,
      _this = this;
    this.currentSection = $('#content > section')[0];
    this.upatePositions = function() {
      var element, position, _i, _len, _ref, _results;
      this.yPositions = [];
      _ref = $('#content > section');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        position = $(element).position();
        _results.push(this.yPositions.push(position.top));
      }
      return _results;
    };
    this.upatePositions();
    this.changeSection = function(index) {
      this.currentSection = $('#content > section')[index];
      $('body > header nav li').removeClass('selected');
      return $($('body > header nav li')[index]).addClass('selected');
    };
    image = new Image();
    image.src = 'img/cordova_icon.png';
    $('body > header nav a').click(function(e) {
      var index;
      index = $('body > header nav a').index(e.target);
      $('body').animate({
        scrollTop: _this.yPositions[index]
      }, 'slow');
      return false;
    });
    $(window).resize(function() {
      return _this.upatePositions();
    });
    return $(window).scroll(function(e) {
      var height, index, newSection, scrollPosition, sectionPosition, _i, _len, _ref;
      scrollPosition = $(window).scrollTop();
      height = $(window).height();
      _ref = _this.yPositions;
      for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
        sectionPosition = _ref[index];
        if ((sectionPosition - height / 2) >= scrollPosition) {
          newSection = $('#content > section')[index - 1];
          break;
        } else {
          newSection = $('#content > section')[index];
        }
      }
      if (newSection !== _this.currentSection) {
        return _this.changeSection(index - 1);
      }
    });
  });

}).call(this);
