// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var image;
    image = new Image();
    image.src = 'img/cordova_icon.png';
    return $('body > header nav a').click(function(e) {
      $('body > header nav li').removeClass('selected');
      return $($(e.target).parent()).addClass('selected');
    });
  });

}).call(this);
