// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    paths: {
      "jquery": "//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min"
    },
    shim: {
      "jquery.timeago": {
        "deps": ["jquery"]
      },
      "jquery.client": {
        "deps": ["jquery"]
      },
      "jquery.popover": {
        "deps": ["jquery"]
      }
    }
  });

  require(['jquery', 'mustache', 'text!data.json', 'text!templates/download.html', 'text!templates/build_list.html', 'text!templates/not_supported.html', 'jquery.timeago', 'jquery.client'], function($, Mustache, jsonData, downloadTemplate, buildListTemplate, notSupportedTemplate) {
    var build, builds, buildsListHTML, download, downloadsHTML, os, _i, _len, _ref;
    $('html').click(function() {
      return $('#downloads-list').removeClass('show');
    });
    $('#content a.other').click(function(event) {
      $('#downloads-list').toggleClass('show');
      event.stopPropagation();
      return false;
    });
    $('#downloads-list').click(function(event) {
      event.stopPropagation();
      return false;
    });
    builds = {
      list: JSON.parse(jsonData)
    };
    _ref = builds.list;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      build = _ref[_i];
      build.date = $.timeago(new Date(build.date));
    }
    switch ($.client.os) {
      case "Mac":
        download = {
          sprint: builds.list[0].sprint,
          date: builds.list[0].date,
          notes: builds.list[0].notes,
          os: $.client.os,
          url: builds.list[0].links[$.client.os].url,
          filetype: builds.list[0].links[$.client.os].filetype,
          filename: builds.list[0].links[$.client.os].filename,
          filesize: builds.list[0].links[$.client.os].filesize
        };
        downloadsHTML = Mustache.render(downloadTemplate, download);
        $('#content header').append(downloadsHTML);
        buildsListHTML = Mustache.render(buildListTemplate, builds);
        return $('#downloads-list').html(buildsListHTML);
      case "Windows":
      case "Win":
        os = "Windows";
        download = {
          sprint: builds.list[0].sprint,
          date: builds.list[0].date,
          notes: builds.list[0].notes,
          os: $.client.os,
          url: builds.list[0].links[os].url,
          filetype: builds.list[0].links[os].filetype,
          filename: builds.list[0].links[os].filename,
          filesize: builds.list[0].links[os].filesize
        };
        downloadsHTML = Mustache.render(downloadTemplate, download);
        $('#content header').append(downloadsHTML);
        buildsListHTML = Mustache.render(buildListTemplate, builds);
        $('#downloads-list').html(buildsListHTML);
        return $('#content > header > img').attr('src', 'img/sprint_17_screenshot_win_@2X.png');
      default:
        $('#content header').append(notSupportedTemplate);
        buildsListHTML = Mustache.render(buildListTemplate, builds);
        $('#downloads-list').html(buildsListHTML);
        return $('#downloads-list').addClass('show');
    }
  });

}).call(this);
