// Generated by CoffeeScript 1.4.0
(function() {
  var currentIndex, refresh;

  refresh = function(findex) {
    var codeBlocks, index, leftCodeBlocks, rightCodeBlocks, selectedCodeBlock;
    if (findex == null) {
      findex = -1;
    }
    if (findex > -1) {
      index = findex;
      $('.inline-editor header li').removeClass('selected');
      $($('.inline-editor header li')[index]).addClass('selected');
    } else {
      index = currentIndex();
    }
    codeBlocks = $('.inline-editor .infinte_editor .codeblock');
    selectedCodeBlock = codeBlocks[index];
    $(selectedCodeBlock).removeClass('left right');
    $('.inline-editor .infinte_editor').height($(selectedCodeBlock).height());
    if (index > 0) {
      leftCodeBlocks = codeBlocks.slice(0, index);
      leftCodeBlocks.removeClass('right');
      leftCodeBlocks.addClass('left');
    }
    if (index + 1 < codeBlocks.length) {
      rightCodeBlocks = codeBlocks.slice(index + 1);
      rightCodeBlocks.removeClass('left');
      return rightCodeBlocks.addClass('right');
    }
  };

  currentIndex = function() {
    return parseInt($('.inline-editor header a').index($('.inline-editor header .selected a')));
  };

  $(function() {
    refresh();
    $(document).bind('keydown', 'j', function() {
      var index;
      index = currentIndex();
      if (index - 1 >= 0) {
        return refresh(index - 1);
      }
    });
    $(document).bind('keydown', 'k', function() {
      console.log(currentIndex() + 2);
      console.log($('.inline-editor .infinte_editor .codeblock').length);
      if (currentIndex() + 2 <= $('.inline-editor .infinte_editor .codeblock').length) {
        return refresh(currentIndex() + 1);
      }
    });
    return $('.inline-editor header a').click(function(e) {
      var index;
      index = $('.inline-editor header a').index(e.target);
      return refresh(index);
    });
  });

}).call(this);
