// Generated by CoffeeScript 1.3.3
(function() {
  var initColor;

  initColor = 'rgb(80, 10, 100)';

  require(['color-editor'], function(ColorEditor) {
    var colorEditor;
    colorEditor = new ColorEditor($('.coloreditor')[0], initColor);
    return $(function() {
      return $('#clickButton').click(function() {
        return colorEditor.parseColor($('#colorInput').val());
      });
    });
  });

}).call(this);
