// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return $('#tab-space-toggle label').click(function() {
      return $('#tab-space-toggle label').toggleClass('selected');
    });
  });

}).call(this);
