// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $('#tab-space-toggle label').click(function() {
      return $('#tab-space-toggle label').toggleClass('selected');
    });
    $('#tab-width label').click(function() {
      $('#tab-width > *').toggleClass('hidden');
      return $('#tab-width input').focus();
    });
    $('#tab-width input').blur(function() {
      $('#tab-width > *').toggleClass('hidden');
      return $('#tab-width label').html($('#tab-width input').val());
    });
    return $('#tab-width input').keyup(function() {
      if (event.keyCode === 13) {
        return $('#tab-width input').blur();
      }
    });
  });

}).call(this);
